# Generated by Django 4.2.1 on 2024-11-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_remove_flashcard_is_hidden_flashcard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
